moeda = input("Digite uma moeda (ex: Dólar, Real):")
qnt_moeda = int(input("Digite a quantidade dessa moeda:"))
valor_moeda = float(input("Digite quanto vale essa moeda:"))
total = (qnt_moeda * valor_moeda)
print("Moeda escolhida: ", moeda, ", Quantidade: ", qnt_moeda, ", Valor atual da moeda: ",valor_moeda, "\nTotal:", total)